/* cppheaders.h - Provides all known boost cpp headers

   Copyright (c) 2017 Grant Rostig. All rights reserved.
   License: Boost v1.0

   Inspired by: 

   Shows how to:
   - Just include everything until modules is working properly and easily. :)
   - 

 */

#pragma once 

/* Boost Library header files
   The interface of C++ standard library is defined by the following collection of header files
 */

//#include <boost/aligned_storage.hpp>  // strange Q error caused me to remove todo
//#include <boost/align.hpp>  // strange Q error caused me to remove todo
//#include <boost/any.hpp>
//#include <boost/array.hpp>
//#include <boost/asio.hpp>
//#include <boost/assert.hpp>
//#include <boost/assign.hpp>
//#include <boost/atomic.hpp>
#include <boost/bimap.hpp>
//#include <boost/bind.hpp>
//#include <boost/blank_fwd.hpp>
//#include <boost/blank.hpp>
//#include <boost/call_traits.hpp>
//#include <boost/cast.hpp>
//#include <boost/cerrno.hpp>
//#include <boost/checked_delete.hpp>
#include <boost/chrono.hpp>
//#include <boost/circular_buffer_fwd.hpp>
//#include <boost/circular_buffer.hpp>
//#include <boost/compressed_pair.hpp>
// sudo apt-get install opencl-headers
// #include <boost/compute.hpp>
//#include <boost/concept_archetype.hpp>
//#include <boost/concept_check.hpp>
//#include <boost/config.hpp>
//#include <boost/convert.hpp>
//#include <boost/crc.hpp>
//#include <boost/cregex.hpp>
//#include <boost/cstdfloat.hpp>
//#include <boost/cstdint.hpp>
//#include <boost/cstdlib.hpp>
//#include <boost/current_function.hpp>
//#include <boost/cxx11_char_types.hpp>
#include <boost/date_time.hpp>
//#include <boost/dll.hpp>
//#include <boost/dynamic_bitset_fwd.hpp>
//#include <boost/dynamic_bitset.hpp>
//#include <boost/enable_shared_from_this.hpp>
//#include <boost/exception_ptr.hpp>
//#include <boost/filesystem.hpp>
#include <boost/flyweight.hpp>
//#include <boost/foreach_fwd.hpp>
//#include <boost/foreach.hpp>
#include <boost/format.hpp>
//#include <boost/functional.hpp>
//#include <boost/function_equal.hpp>
//#include <boost/function.hpp>
//#include <boost/function_output_iterator.hpp>
//#include <boost/generator_iterator.hpp>
//#include <boost/geometry.hpp>
//#include <boost/get_pointer.hpp>
//#include <boost/hana.hpp>
//#include <boost/implicit_cast.hpp>
//#include <boost/indirect_reference.hpp>
//#include <boost/integer_fwd.hpp>
//#include <boost/integer.hpp>
//#include <boost/integer_traits.hpp>
//#include <boost/intrusive_ptr.hpp>
//#include <boost/io_fwd.hpp>
//#include <boost/is_placeholder.hpp>
//#include <boost/iterator_adaptors.hpp>
//#include <boost/iterator.hpp>
//#include <boost/last_value.hpp>
//#include <boost/lexical_cast.hpp>
//#include <boost/limits.hpp>
//#include <boost/locale.hpp>
//#include <boost/local_function.hpp>
//#include <boost/make_default.hpp>
//#include <boost/make_shared.hpp>
//#include <boost/make_unique.hpp>
//#include <boost/math_fwd.hpp>
//#include <boost/mem_fn.hpp>
//#include <boost/memory_order.hpp>
//#include <boost/metaparse.hpp>
//#include <boost/mpi.hpp>
//#include <boost/multi_array.hpp>
//#include <boost/multi_index_container_fwd.hpp>
//#include <boost/multi_index_container.hpp>
//#include <boost/next_prior.hpp>
//#include <boost/noncopyable.hpp>
//#include <boost/nondet_random.hpp>
//#include <boost/none.hpp>
//#include <boost/none_t.hpp>
//#include <boost/non_type.hpp>
//#include <boost/operators.hpp>
//#include <boost/operators_v1.hpp>
//#include <boost/optional.hpp>
//#include <boost/parameter.hpp>
//#include <boost/phoenix.hpp>
//#include <boost/pointee.hpp>
//#include <boost/pointer_cast.hpp>
//#include <boost/pointer_to_other.hpp>
//#include <boost/polymorphic_cast.hpp>
//#include <boost/polymorphic_pointer_cast.hpp>
//#include <boost/predef.h>
//#include <boost/preprocessor.hpp>
#include <boost/program_options.hpp>
//#include <boost/progress.hpp>
//#include <boost/python.hpp>
//#include <boost/random.hpp>
//#include <boost/range.hpp>
//#include <boost/ratio.hpp>
//#include <boost/rational.hpp>
//#include <boost/ref.hpp>
//#include <boost/regex_fwd.hpp>
//#include <boost/regex.h>
//#include <boost/regex.hpp>
//#include <boost/scoped_array.hpp>
//#include <boost/scoped_ptr.hpp>
//#include <boost/scope_exit.hpp>
//#include <boost/shared_array.hpp>
//#include <boost/shared_container_iterator.hpp>
//#include <boost/shared_ptr.hpp>
//#include <boost/signal.hpp>
//#include <boost/signals2.hpp>
//#include <boost/signals.hpp>
//#include <boost/smart_ptr.hpp>
//#include <boost/spirit.hpp>
//#include <boost/static_assert.hpp>
//#include <boost/swap.hpp>
//#include <boost/thread.hpp>
//#include <boost/throw_exception.hpp>
//#include <boost/timer.hpp>  // Obsolete version!! use header in subdirectory below
//#include <boost/token_functions.hpp>
//#include <boost/token_iterator.hpp>
//#include <boost/tokenizer.hpp>
//#include <boost/type.hpp>
//#include <boost/type_index.hpp>
//#include <boost/type_traits.hpp>
//#include <boost/unordered_map.hpp>
//#include <boost/unordered_set.hpp>
//#include <boost/utility.hpp>
//#include <boost/variant.hpp>
//#include <boost/version.hpp>
//#include <boost/visit_each.hpp>
//#include <boost/wave.hpp>
//#include <boost/weak_ptr.hpp>

//#include <boost/accumulators/>
//#include <boost/algorithm/>
//#include <boost/align/>
//#include <boost/archive/>
//#include <boost/asio/>
//#include <boost/assign/>
//#include <boost/atomic/>
//#include <boost/bimap/>
//#include <boost/bind/>
//#include <boost/chrono/>
//#include <boost/circular_buffer/>
//#include <boost/compatibility/>
//#include <boost/compute/>
//#include <boost/concept/>
//#include <boost/concept_check/>
//#include <boost/config/>
//#include <boost/container/>
//#include <boost/context/>
//#include <boost/convert/>
//#include <boost/core/>
//#include <boost/coroutine/>
//#include <boost/coroutine2/>
//#include <boost/date_time/>
//#include <boost/detail/>
//#include <boost/dll/>
//#include <boost/dynamic_bitset/>
//#include <boost/endian/>
//#include <boost/exception/>
//#include <boost/fiber/>
//#include <boost/filesystem/>
//#include <boost/flyweight/>
//#include <boost/format/>
//#include <boost/function/>
//#include <boost/functional/>
//#include <boost/function_types/>
//#include <boost/fusion/>
//#include <boost/geometry/>
//#include <boost/gil/>
//#include <boost/graph/>
//#include <boost/hana/>
//#include <boost/heap/>
//#include <boost/icl/>
//#include <boost/integer/>
//#include <boost/interprocess/>
//#include <boost/intrusive/>
//#include <boost/io/>
//#include <boost/iostreams/>
//#include <boost/iterator/>
//#include <boost/lambda/>
//#include <boost/lexical_cast/>
//#include <boost/locale/>
//#include <boost/local_function/>
//#include <boost/lockfree/>

//#include <boost/log/>
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
/*
void boost_log_init()
{
    boost::log::core::get()->set_filter
    (
        boost::log::trivial::severity >= logging::trivial::info
    );
}
    BOOST_LOG_TRIVIAL(trace) << "A trace severity message";
    BOOST_LOG_TRIVIAL(debug) << "A debug severity message";
    BOOST_LOG_TRIVIAL(info) << "An informational severity message";
    BOOST_LOG_TRIVIAL(warning) << "A warning severity message";
    BOOST_LOG_TRIVIAL(error) << "An error severity message";
    BOOST_LOG_TRIVIAL(fatal) << "A fatal severity message";
*/

//#include <boost/logic/>
//#include <boost/math/>  See below for expansion of 311 lines!
//#include <boost/metaparse/>
//#include <boost/move/>
//#include <boost/mpi/>
//#include <boost/mpl/>
//#include <boost/msm/>
//#include <boost/multi_array/>
//#include <boost/multi_index/>
//#include <boost/multiprecision/>
//#include <boost/numeric/>
//#include <boost/optional/>
//#include <boost/parameter/>
//#include <boost/pending/>
//#include <boost/phoenix/>
//#include <boost/polygon/>
//#include <boost/pool/>
//#include <boost/predef/>
//#include <boost/preprocessor/>
//#include <boost/program_options/>
//#include <boost/property_map/>

//#include <boost/property_tree/>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/info_parser.hpp>

//#include <boost/proto/>
//#include <boost/ptr_container/>
//#include <boost/python/>
//#include <boost/qvm/>
//#include <boost/random/>
//#include <boost/range/>
//#include <boost/ratio/>
//#include <boost/regex/>
//#include <boost/serialization/>
#include <boost/serialization/strong_typedef.hpp>
//#include <boost/signals/>
//#include <boost/signals2/>
//#include <boost/smart_ptr/>
//#include <boost/sort/>
//#include <boost/spirit/>
//#include <boost/statechart/>
//#include <boost/system/>

//#define BOOST_TEST_DYN_LINK
//#define BOOST_TEST_MODULE Grostig_Default_Test_from_boost_headers.h
// run executable using >> --log_level=test_suite <<
//#include <boost/test/>
//#include <boost/test/unit_test.hpp>

//#include <boost/thread/>
#include <boost/timer/timer.hpp> // current version (not the obsolete one above)
//#include <boost/tr1/>
//#include <boost/tti/>
//#include <boost/tuple/>
//#include <boost/type_erasure/>
//#include <boost/type_index/>
//#include <boost/typeof/>
//#include <boost/type_traits/>
//#include <boost/units/>
//#include <boost/unordered/>
//#include <boost/utility/>
//#include <boost/uuid/>
//#include <boost/variant/>
//#include <boost/vmd/>
//#include <boost/wave/>
//#include <boost/xpressive/>
//#include </usr/include/boost/math/concepts/real_concept.hpp>
//#include </usr/include/boost/math/concepts/distributions.hpp>
//#include </usr/include/boost/math/concepts/std_real_concept.hpp>
//#include </usr/include/boost/math/concepts/real_type_concept.hpp>
//#include </usr/include/boost/math/policies/error_handling.hpp>
//#include </usr/include/boost/math/policies/policy.hpp>
//#include </usr/include/boost/math/tools/roots.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_10.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_15.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_2.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_5.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_9.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_11.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_11.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_19.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_9.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_10.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_9.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_19.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_18.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_6.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_20.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_17.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_9.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_2.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_5.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_3.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_8.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_12.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_13.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_18.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_20.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_15.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_11.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_17.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_11.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_12.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_19.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_13.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_14.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_3.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_16.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_19.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_2.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_5.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_7.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_14.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_15.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_7.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_4.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_10.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_4.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_6.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_2.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_7.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_13.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_19.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_3.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_6.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_17.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_16.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_8.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_13.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_12.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_11.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_12.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_6.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_13.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_9.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_20.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_10.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_4.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_4.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_3.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_20.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_20.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_14.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_14.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_17.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_5.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_5.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_15.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_16.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_9.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_20.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_14.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_16.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_8.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_2.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_4.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_7.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_12.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_15.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_8.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_18.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_11.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner2_18.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_18.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_16.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_12.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_16.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner2_15.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_5.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_17.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_7.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_10.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_2.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_8.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_7.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_10.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_3.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_13.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_8.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_6.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_18.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_19.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner1_6.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner1_14.hpp>
//#include </usr/include/boost/math/tools/detail/polynomial_horner3_4.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_3.hpp>
//#include </usr/include/boost/math/tools/detail/rational_horner3_17.hpp>
//#include </usr/include/boost/math/tools/fraction.hpp>
//#include </usr/include/boost/math/tools/tuple.hpp>
//#include </usr/include/boost/math/tools/convert_from_string.hpp>
//#include </usr/include/boost/math/tools/config.hpp>
//#include </usr/include/boost/math/tools/series.hpp>
//#include </usr/include/boost/math/tools/big_constant.hpp>
//#include </usr/include/boost/math/tools/promotion.hpp>
//#include </usr/include/boost/math/tools/workaround.hpp>
//#include </usr/include/boost/math/tools/toms748_solve.hpp>
//#include </usr/include/boost/math/tools/polynomial.hpp>
//#include </usr/include/boost/math/tools/real_cast.hpp>
//#include </usr/include/boost/math/tools/minima.hpp>
//#include </usr/include/boost/math/tools/user.hpp>
//#include </usr/include/boost/math/tools/stats.hpp>
//#include </usr/include/boost/math/tools/precision.hpp>
//#include </usr/include/boost/math/tools/traits.hpp>
//#include </usr/include/boost/math/tools/rational.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_types.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_complex_std.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_iostream.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_complex.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_cmath.hpp>
//#include </usr/include/boost/math/cstdfloat/cstdfloat_limits.hpp>
//#include </usr/include/boost/math/distributions/beta.hpp>
//#include </usr/include/boost/math/distributions/geometric.hpp>
//#include </usr/include/boost/math/distributions/triangular.hpp>
//#include </usr/include/boost/math/distributions/detail/inv_discrete_quantile.hpp>
//#include </usr/include/boost/math/distributions/detail/hypergeometric_cdf.hpp>
//#include </usr/include/boost/math/distributions/detail/generic_mode.hpp>
//#include </usr/include/boost/math/distributions/detail/common_error_handling.hpp>
//#include </usr/include/boost/math/distributions/detail/generic_quantile.hpp>
//#include </usr/include/boost/math/distributions/detail/hypergeometric_quantile.hpp>
//#include </usr/include/boost/math/distributions/detail/hypergeometric_pdf.hpp>
//#include </usr/include/boost/math/distributions/detail/derived_accessors.hpp>
//#include </usr/include/boost/math/distributions/pareto.hpp>
//#include </usr/include/boost/math/distributions/find_scale.hpp>
//#include </usr/include/boost/math/distributions/arcsine.hpp>
//#include </usr/include/boost/math/distributions/bernoulli.hpp>
//#include </usr/include/boost/math/distributions/logistic.hpp>
//#include </usr/include/boost/math/distributions/non_central_beta.hpp>
//#include </usr/include/boost/math/distributions/weibull.hpp>
//#include </usr/include/boost/math/distributions/poisson.hpp>
//#include </usr/include/boost/math/distributions/non_central_f.hpp>
//#include </usr/include/boost/math/distributions/cauchy.hpp>
//#include </usr/include/boost/math/distributions/non_central_chi_squared.hpp>
//#include </usr/include/boost/math/distributions/exponential.hpp>
//#include </usr/include/boost/math/distributions/skew_normal.hpp>
//#include </usr/include/boost/math/distributions/chi_squared.hpp>
//#include </usr/include/boost/math/distributions/inverse_gamma.hpp>
//#include </usr/include/boost/math/distributions/uniform.hpp>
//#include </usr/include/boost/math/distributions/non_central_t.hpp>
//#include </usr/include/boost/math/distributions/gamma.hpp>
//#include </usr/include/boost/math/distributions/extreme_value.hpp>
//#include </usr/include/boost/math/distributions/complement.hpp>
//#include </usr/include/boost/math/distributions/normal.hpp>
//#include </usr/include/boost/math/distributions/inverse_chi_squared.hpp>
//#include </usr/include/boost/math/distributions/hyperexponential.hpp>
//#include </usr/include/boost/math/distributions/laplace.hpp>
//#include </usr/include/boost/math/distributions/hypergeometric.hpp>
//#include </usr/include/boost/math/distributions/binomial.hpp>
//#include </usr/include/boost/math/distributions/inverse_gaussian.hpp>
//#include </usr/include/boost/math/distributions/rayleigh.hpp>
//#include </usr/include/boost/math/distributions/lognormal.hpp>
//#include </usr/include/boost/math/distributions/students_t.hpp>
//#include </usr/include/boost/math/distributions/fisher_f.hpp>
//#include </usr/include/boost/math/distributions/negative_binomial.hpp>
//#include </usr/include/boost/math/distributions/fwd.hpp>
//#include </usr/include/boost/math/distributions/find_location.hpp>
//#include </usr/include/boost/math/constants/info.hpp>
#include </usr/include/boost/math/constants/constants.hpp>
//#include </usr/include/boost/math/constants/calculate_constants.hpp>
//#include </usr/include/boost/math/octonion.hpp>
//#include </usr/include/boost/math/tr1_c_macros.ipp>
//#include </usr/include/boost/math/common_factor_ct.hpp>
//#include </usr/include/boost/math/bindings/detail/big_lanczos.hpp>
//#include </usr/include/boost/math/bindings/detail/big_digamma.hpp>
//#include </usr/include/boost/math/bindings/mpreal.hpp>
//#include </usr/include/boost/math/bindings/mpfr.hpp>
//#include </usr/include/boost/math/bindings/e_float.hpp>
//#include </usr/include/boost/math/bindings/rr.hpp>
//#include </usr/include/boost/math/special_functions/cbrt.hpp>
//#include </usr/include/boost/math/special_functions/pow.hpp>
//#include </usr/include/boost/math/special_functions/beta.hpp>
//#include </usr/include/boost/math/special_functions/polygamma.hpp>
//#include </usr/include/boost/math/special_functions/detail/round_fwd.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_ik.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy_derivatives_series.hpp>
//#include </usr/include/boost/math/special_functions/detail/polygamma.hpp>
//#include </usr/include/boost/math/special_functions/detail/unchecked_bernoulli.hpp>
//#include </usr/include/boost/math/special_functions/detail/lgamma_small.hpp>
//#include </usr/include/boost/math/special_functions/detail/gamma_inva.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy_series.hpp>
//#include </usr/include/boost/math/special_functions/detail/iconv.hpp>
//#include </usr/include/boost/math/special_functions/detail/igamma_large.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy_derivatives_asym.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_kn.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jn.hpp>
//#include </usr/include/boost/math/special_functions/detail/igamma_inverse.hpp>
//#include </usr/include/boost/math/special_functions/detail/unchecked_factorial.hpp>
//#include </usr/include/boost/math/special_functions/detail/ibeta_inverse.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_k0.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_i0.hpp>
//#include </usr/include/boost/math/special_functions/detail/fp_traits.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy_asym.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy_zero.hpp>
//#include </usr/include/boost/math/special_functions/detail/ibeta_inv_ab.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_derivatives_linear.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_k1.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_i1.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_yn.hpp>
//#include </usr/include/boost/math/special_functions/detail/airy_ai_bi_zero.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_y1.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_j0.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_jy.hpp>
//#include </usr/include/boost/math/special_functions/detail/t_distribution_inv.hpp>
//#include </usr/include/boost/math/special_functions/detail/erf_inv.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_j1.hpp>
//#include </usr/include/boost/math/special_functions/detail/lanczos_sse2.hpp>
//#include </usr/include/boost/math/special_functions/detail/bessel_y0.hpp>
//#include </usr/include/boost/math/special_functions/detail/bernoulli_details.hpp>
//#include </usr/include/boost/math/special_functions/modf.hpp>
//#include </usr/include/boost/math/special_functions/ellint_rg.hpp>
//#include </usr/include/boost/math/special_functions/ellint_1.hpp>
//#include </usr/include/boost/math/special_functions/atanh.hpp>
//#include </usr/include/boost/math/special_functions/lanczos.hpp>
//#include </usr/include/boost/math/special_functions/ellint_d.hpp>
//#include </usr/include/boost/math/special_functions/asinh.hpp>
//#include </usr/include/boost/math/special_functions/ellint_rd.hpp>
//#include </usr/include/boost/math/special_functions/next.hpp>
//#include </usr/include/boost/math/special_functions/ellint_3.hpp>
//#include </usr/include/boost/math/special_functions/relative_difference.hpp>
//#include </usr/include/boost/math/special_functions/owens_t.hpp>
//#include </usr/include/boost/math/special_functions/sin_pi.hpp>
//#include </usr/include/boost/math/special_functions/bernoulli.hpp>
//#include </usr/include/boost/math/special_functions/cos_pi.hpp>
//#include </usr/include/boost/math/special_functions/powm1.hpp>
//#include </usr/include/boost/math/special_functions/ellint_rf.hpp>
//#include </usr/include/boost/math/special_functions/expint.hpp>
//#include </usr/include/boost/math/special_functions/fpclassify.hpp>
//#include </usr/include/boost/math/special_functions/jacobi_zeta.hpp>
//#include </usr/include/boost/math/special_functions/ellint_rj.hpp>
#include </usr/include/boost/math/special_functions/sign.hpp>
//#include </usr/include/boost/math/special_functions/zeta.hpp>
//#include </usr/include/boost/math/special_functions/digamma.hpp>
//#include </usr/include/boost/math/special_functions/prime.hpp>
//#include </usr/include/boost/math/special_functions/airy.hpp>
//#include </usr/include/boost/math/special_functions/ellint_rc.hpp>
//#include </usr/include/boost/math/special_functions/math_fwd.hpp>
//#include </usr/include/boost/math/special_functions/legendre.hpp>
//#include </usr/include/boost/math/special_functions/gamma.hpp>
//#include </usr/include/boost/math/special_functions/spherical_harmonic.hpp>
//#include </usr/include/boost/math/special_functions/sqrt1pm1.hpp>
//#include </usr/include/boost/math/special_functions/heuman_lambda.hpp>
//#include </usr/include/boost/math/special_functions/bessel.hpp>
//#include </usr/include/boost/math/special_functions/hypot.hpp>
//#include </usr/include/boost/math/special_functions/bessel_prime.hpp>
//#include </usr/include/boost/math/special_functions/hankel.hpp>
//#include </usr/include/boost/math/special_functions/jacobi_elliptic.hpp>
//#include </usr/include/boost/math/special_functions/expm1.hpp>
//#include </usr/include/boost/math/special_functions/factorials.hpp>
//#include </usr/include/boost/math/special_functions/round.hpp>
//#include </usr/include/boost/math/special_functions/sinc.hpp>
//#include </usr/include/boost/math/special_functions/ellint_2.hpp>
//#include </usr/include/boost/math/special_functions/trunc.hpp>
//#include </usr/include/boost/math/special_functions/hermite.hpp>
//#include </usr/include/boost/math/special_functions/sinhc.hpp>
//#include </usr/include/boost/math/special_functions/erf.hpp>
//#include </usr/include/boost/math/special_functions/trigamma.hpp>
//#include </usr/include/boost/math/special_functions/acosh.hpp>
//#include </usr/include/boost/math/special_functions/binomial.hpp>
//#include </usr/include/boost/math/special_functions/ulp.hpp>
//#include </usr/include/boost/math/special_functions/nonfinite_num_facets.hpp>
//#include </usr/include/boost/math/special_functions/log1p.hpp>
//#include </usr/include/boost/math/special_functions/laguerre.hpp>
//#include </usr/include/boost/math/complex.hpp>
//#include </usr/include/boost/math/distributions.hpp>
//#include </usr/include/boost/math/special_functions.hpp>
//#include </usr/include/boost/math/common_factor.hpp>
//#include </usr/include/boost/math/tr1.hpp>
//#include </usr/include/boost/math/common_factor_rt.hpp>
//#include </usr/include/boost/math/complex/atanh.hpp>
//#include </usr/include/boost/math/complex/fabs.hpp>
//#include </usr/include/boost/math/complex/atan.hpp>
//#include </usr/include/boost/math/complex/asinh.hpp>
//#include </usr/include/boost/math/complex/asin.hpp>
//#include </usr/include/boost/math/complex/acos.hpp>
//#include </usr/include/boost/math/complex/acosh.hpp>
//#include </usr/include/boost/math/complex/details.hpp>
//#include </usr/include/boost/math/quaternion.hpp>
