# ChatGPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
###############################################################################
# Core C/C++ Build Artifacts (Cross-Platform)
###############################################################################
# Object files
*.o
*.obj
*.lo
*.la
*.al
*.pch
*.gch
# Libraries
*.a
*.lib
*.so
*.so.*
*.dylib
*.dll
# Executables
*.exe
*.out
*.app
# Debug / symbol files
*.pdb
*.idb
*.ilk
*.dSYM/
*.su
# Coverage / profiling
*.gcno
*.gcda
*.gcov
*.prof
*.profraw
*.profdata
# Temporary
*.tmp
*.temp
*.log
*.cache
*.bak
*.swp
*.swo
*~
###############################################################################
# CMake (all generators, standalone or IDE driven)
###############################################################################
# Build directories (recommended out-of-source builds)
build/
build-*/
cmake-build-*/
out/
bin/
lib/
# CMake generated files
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake
Testing/
Makefile
CMakeScripts/
_deps/
###############################################################################
# Visual Studio (native projects + CMake integration)
###############################################################################
# VS user files
.vs/
*.VC.db
*.VC.opendb
*.VC.VC.opendb
*.suo
*.user
*.userosscache
*.sln.docstates
# MSBuild
*.tlog
*.lastbuildstate
ipch/
# Visual Studio CMake
CMakeSettings.json
CMakeUserPresets.json
###############################################################################
# VS Code
###############################################################################
.vscode/
*.code-workspace
###############################################################################
# Qt Creator (qmake + CMake)
###############################################################################
# Qt Creator project user files
*.pro.user
*.pro.user.*
*.pri.user
*.creator
*.creator.user
*.creator.user.*
# qmake
Makefile*
*.moc
moc_*.cpp
qrc_*.cpp
ui_*.h
###############################################################################
# GNU Make / Generic Make
###############################################################################
# Dependency files
*.d
###############################################################################
# Autotools
###############################################################################
# Generated by autotools
aclocal.m4
autom4te.cache/
configure
config.log
config.status
config.guess
config.sub
libtool
ltmain.sh
missing
m4/
Makefile.in
depcomp
compile
install-sh
###############################################################################
# Vim
###############################################################################
.*.swp
.*.swo
Session.vim
###############################################################################
# Platform Specific
###############################################################################
# Windows
Thumbs.db
Desktop.ini
# Linux
*.stackdump
###############################################################################
# Archives / Packages
###############################################################################
*.zip
*.tar
*.tar.gz
*.tgz
*.7z
###############################################################################
# Clang / GCC tooling
###############################################################################
.clangd/
.clang-tidy
.clang-format.cache
###############################################################################
# Python (sometimes used for build tooling)
###############################################################################
__pycache__/
*.pyc

# Claude ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# ==============================================================================
# Comprehensive C++ .gitignore
# ==============================================================================
# Covers: CMake, Visual Studio, VS Code, Qt Creator (qmake/CMake),
#         Make, Autotools, Vim - Linux & Windows platforms
# ------------------------------------------------------------------------------
# C++ Compiled Object Files and Libraries
# ------------------------------------------------------------------------------
*.o
*.obj
*.ko
*.elf
*.a
*.lib
*.so
*.so.*
*.dylib
*.dll
*.exe
*.out
*.app
# ------------------------------------------------------------------------------
# C++ Precompiled Headers
# ------------------------------------------------------------------------------
*.gch
*.pch
# ------------------------------------------------------------------------------
# Debug and Symbol Files
# ------------------------------------------------------------------------------
*.pdb
*.ilk
*.idb
*.iobj
*.ipdb
*.exp
*.dSYM/
*.su
*.stackdump
core
core.*
# ------------------------------------------------------------------------------
# CMake Build System
# ------------------------------------------------------------------------------
CMakeCache.txt
CMakeFiles/
CMakeScripts/
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake
_deps/
*.cmake
!CMakeLists.txt
!*Config.cmake
!*ConfigVersion.cmake
!*Targets.cmake
# CMake build directories (common patterns)
build/
Build/
builds/
cmake-build-*/
out/
Out/
# ------------------------------------------------------------------------------
# Visual Studio (Native Solutions and CMake)
# ------------------------------------------------------------------------------
# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates
# User-specific directories
.vs/
.vscode/launch.json
.vscode/tasks.json
# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/
# Visual Studio profiler
*.psess
*.vsp
*.vspx
*.sap
# Visual Studio Trace Files
*.e2e
# TFS 2012 Local Workspace
$tf/
# ReSharper
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user
# TeamCity
_TeamCity*
# NCrunch
_NCrunch_*
.*crunch*.local.xml
nCrunchTemp_*
# Visual Studio code coverage results
*.coverage
*.coveragexml
# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*
# NUnit
*.VisualState.xml
TestResult.xml
nunit-*.xml
# Build Results of an ATL Project
[Dd]ebugPS/
[Rr]eleasePS/
dlldata.c
# Benchmark Results
BenchmarkDotNet.Artifacts/
# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
# ASP.NET Scaffolding
ScaffoldingReadMe.txt
# Files built by Visual Studio
*_i.c
*_p.c
*_h.h
*.meta
*.iobj
*.ipdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*_wpftmp.csproj
*.log
*.tlog
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc
# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.VC.db
*.VC.VC.opendb
# Visual Studio profiler
*.psess
*.vsp
*.vspx
*.sap
# Visual Studio Trace Files
*.e2e
# Installshield output folder
[Ee]xpress/
# DocProject
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html
# Click-Once directory
publish/
# Publish Web Output
*.[Pp]ublish.xml
*.azurePubxml
*.pubxml
*.publishproj
# Microsoft Azure Web App publish settings
PublishScripts/
# NuGet Packages
*.nupkg
*.snupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nuget.props
*.nuget.targets
# Windows Store app package directories and files
AppPackages/
BundleArtifacts/
Package.StoreAssociation.xml
_pkginfo.txt
*.appx
*.appxbundle
*.appxupload
# Visual Studio cache files
*.suo
*.user
*.sln.docstates
# Windows image file caches
Thumbs.db
ehthumbs.db
# Folder config file
Desktop.ini
# Recycle Bin
$RECYCLE.BIN/
# VS Code directories
.vscode/
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
*.code-workspace
# Local History for Visual Studio Code
.history/
# Built Visual Studio Code Extensions
*.vsix
# ------------------------------------------------------------------------------
# Qt Creator (qmake and CMake)
# ------------------------------------------------------------------------------
*.pro.user
*.pro.user.*
*.qbs.user
*.qbs.user.*
*.moc
moc_*.cpp
moc_*.h
qrc_*.cpp
ui_*.h
*.qmlc
*.jsc
Makefile*
*build-*
*.autosave
.qmake.stash
# Qt Creator local configuration
qtcreator-*.pro.user*
# Qt Creator CMake
CMakeLists.txt.user*
# QtCreator 4.8< compilation database
compile_commands.json
# QtCreator local machine specific files for imported projects
*creator.user*
*_qmlcache.qrc
# ------------------------------------------------------------------------------
# GNU Make
# ------------------------------------------------------------------------------
Makefile
!*/Makefile
!Makefile.am
!Makefile.in
*.make
.depend
# ------------------------------------------------------------------------------
# GNU Autotools
# ------------------------------------------------------------------------------
/autom4te.cache
/aclocal.m4
/compile
/configure
/depcomp
/install-sh
/missing
/stamp-h1
/config.guess
/config.sub
/config.log
/config.status
/libtool
/ltmain.sh
*.la
*.lo
.deps/
.libs/
Makefile.in
*.m4
!m4/
# ------------------------------------------------------------------------------
# Vim Editor
# ------------------------------------------------------------------------------
[._]*.s[a-v][a-z]
!*.svg
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
Session.vim
Sessionx.vim
.netrwhist
*~
tags
[._]*.un~
# ------------------------------------------------------------------------------
# Emacs Editor
# ------------------------------------------------------------------------------
*~
\#*\#
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.\#*
# ------------------------------------------------------------------------------
# Common C++ Package Managers
# ------------------------------------------------------------------------------
# Conan
conan.lock
conanbuildinfo.*
conaninfo.txt
graph_info.json
.conan/
# vcpkg
vcpkg_installed/
vcpkg/
.vcpkg-root
# ------------------------------------------------------------------------------
# Documentation
# ------------------------------------------------------------------------------
/doc/html/
/doc/latex/
Doxyfile.bak
doxygen_sqlite3.db
# ------------------------------------------------------------------------------
# Testing Frameworks
# ------------------------------------------------------------------------------
# Google Test
googletest/
gtest/
gmock/
# Catch2
catch2/
# Test outputs
*.test
test_results/
test_output/
*.gcov
*.gcda
*.gcno
# Coverage
*.coverage
coverage/
lcov.info
*.profdata
*.profraw
# ------------------------------------------------------------------------------
# Sanitizer Outputs
# ------------------------------------------------------------------------------
*.dSYM
*.asan
*.msan
*.tsan
*.ubsan
# ------------------------------------------------------------------------------
# Static Analysis
# ------------------------------------------------------------------------------
.clang-tidy
.clang-format
compile_commands.json
.cache/
.ccls-cache/
# ------------------------------------------------------------------------------
# IDEs and Editors (Additional)
# ------------------------------------------------------------------------------
.idea/
*.iml
*.swp
*.swo
.DS_Store
*.sublime-project
*.sublime-workspace
.project
.cproject
.settings/
# ------------------------------------------------------------------------------
# OS-Specific
# ------------------------------------------------------------------------------
# Windows
*.exe
*.dll
*.pdb
*.ilk
*.exp
*.lib
Thumbs.db
ehthumbs.db
Desktop.ini
# Linux
*.so
*.a
*.out
.fuse_hidden*
.directory
.Trash-*
.nfs*
# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
.AppleDB
.AppleDesktop
# ------------------------------------------------------------------------------
# Build Artifacts and Temporary Files
# ------------------------------------------------------------------------------
*.tmp
*.temp
*.bak
*.backup
*.orig
*.rej
*.swp
*~
.#*
# Dependency directories
third_party/
external/
!external/.gitkeep
vendor/
!vendor/.gitkeep
# ------------------------------------------------------------------------------
# Custom Build Directories (Common Patterns)
# ------------------------------------------------------------------------------
/dist/
/output/
/target/
/bin/
/lib/

# CoPilot ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Consolidated .gitignore for C++ projects
# Targets:
# - VS Code (CMake)
# - Visual Studio 26 (native solutions/projects and CMake)
# - Qt Creator (qmake and CMake)
# - CMake standalone, Make, Autotools
# - Vim / command-line builds
# - Linux and Windows
#
# Place at repository root. Adjust build folder names if you use custom names.
# -------------------------
# OS / general
# -------------------------
# Windows
Thumbs.db
desktop.ini
# macOS
.DS_Store
.AppleDouble
.LSOverride
# Linux
.Trash-*
# Temporary and editor backup files
*~
*.swp
*.swo
*.tmp
*.temp
*.bak
*.orig
# -------------------------
# Editors / IDEs
# -------------------------
# VS Code
.vscode/
*.code-workspace
.vscode-test/
# Visual Studio (including VS 26)
.vs/
*.suo
*.user
*.userosscache
*.sln.docstates
*.VC.db
*.VC.VC.opendb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.psess
*.vsp
*.vspx
# Per-user project files
*.vcxproj.user
*.vcxproj.*.user
# Keep .sln and .vcxproj tracked if you intentionally commit them
# Qt Creator
*.pro.user
*.pro.user.*
*.qmake.stash
*.qmake.cache
*.creator.user
*.creator.user.*
*.autosave
# Qt Creator build dirs (common pattern)
build-*/
# Qt compiled QML
*.qmlc
# JetBrains (CLion etc.)
.idea/
*.iml
# Vim / command-line editor
Session.vim
tags
# Other editors / IDEs
*.sublime-workspace
*.sublime-project
.project
.metadata/
.kdev4/
# -------------------------
# CMake (common)
# -------------------------
# CMake cache and generated files
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
CTestTestfile.cmake
CTestTestfile.cmake.user
Testing/
Makefile.cmake
install_manifest.txt
# Common out-of-source build dirs (adjust names if you use others)
cmake-build-*/
build/
build*/
out/
bin/
lib/
lib64/
obj/
# Ninja
build.ninja
.ninja_deps
.ninja_log
# Visual Studio CMake user settings
CMakeSettings.json.user
# -------------------------
# Make / Autotools / QMake / Meson
# -------------------------
# Autotools generated
config.log
config.status
configure
configure.ac
aclocal.m4
autom4te.cache/
Makefile.in
Makefile~
m4/
ltmain.sh
libtool
*.la
# Make artifacts and generic object files
*.o
*.lo
*.obj
*.a
*.so
*.so.*
*.dylib
*.dll
*.exe
*.out
*.elf
# QMake / Qt build artifacts
Makefile.Debug
Makefile.Release
*.moc
moc_*.cpp
qrc_*.cpp
ui_*.h
# Meson
meson-logs/
meson-private/
builddir/
# -------------------------
# Compiled objects, libs, executables, symbols
# -------------------------
# Object files and modules
*.o
*.ko
*.obj
*.lo
# Static libs
*.a
*.lib
# Shared libs / dynamic
*.so
*.so.*
*.dylib
*.dll
# Executables and bundles
*.exe
*.out
*.app
# Debug / symbol files
*.pdb
*.ilk
*.dSYM/
*.su
*.sym
# -------------------------
# Test, coverage, profiling
# -------------------------
coverage/
*.gcno
*.gcda
*.gcov
*.lcov
*.prof
*.profraw
*.profdata
test-results/
*.tap
*.trx
# -------------------------
# Package managers / caches
# -------------------------
# Conan
conanbuildinfo.*
conaninfo.txt
conan.lock
conan_data/
# vcpkg
vcpkg_installed/
vcpkg/
# Hunter / CPM
_hunter/
.cpm/
# ccache
.ccache/
*.ccache
# -------------------------
# Generated sources / codegen
# -------------------------
# Protobuf / gRPC
*.pb.h
*.pb.cc
*.grpc.pb.h
*.grpc.pb.cc
# Generated directories
generated/
gen/
# SWIG
*.i
*.wrap
# -------------------------
# Logs, runtime, and misc
# -------------------------
*.log
*.trace
*.pid
*.seed
*.stackdump
*.stacktrace
*.traceback
# Secrets / env
*.pem
*.key
*.crt
*.env
.env.local
.env.*.local
.editorconfig.local
# -------------------------
# Platform-specific build folders (common names)
# -------------------------
# Visual Studio build folders
Debug/
Release/
x64/Debug/
x64/Release/
# Common CI / packaging
dist/
pkg/
*.deb
*.rpm
*.tar.gz
*.zip
*.msi
*.msm
*.msp
# -------------------------
# Misc IDE / project files you usually don't track
# -------------------------
.classpath
.metadata/
*~   # Emacs backups (already listed above)
*.sublime-project
*.sublime-workspace
# -------------------------
# Keep these tracked if intentional (uncomment to enforce)
# -------------------------
# !CMakeLists.txt
# !*.sln
# !*.vcxproj
# !README
# !LICENSE
# -------------------------
# Notes
# - If you use a specific build folder name (e.g., "out", "build-debug"), add it explicitly.
# - If you commit generated artifacts intentionally, remove or override the matching patterns.
# - This file focuses on ignoring user-specific, build, and generated files across Linux and Windows.

# Gemini ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# ----------------------------------------------------------------------
# General C++ Compiled Artifacts (Windows & Linux)
# ----------------------------------------------------------------------
# Precompiled Headers
*.gch
*.pch
*.ipch
# Libraries
*.lib
*.a
*.la
*.lai
*.lo
# Shared objects (dynamic libraries)
*.dll
*.so
*.so.*
*.dylib
# Executables
*.exe
*.out
*.app
# Debugging artifacts
*.pdb
*.idb
*.ilkc
*.map
*.exp
*.dSYM/
# ----------------------------------------------------------------------
# Build Directories (Common Naming Conventions)
# ----------------------------------------------------------------------
# It is best practice to ignore root-level build folders entirely
[Bb]uild/
[Bb]uilds/
[Oo]ut/
[Bb]in/
[Dd]ebug/
[Rr]elease/
x64/
x86/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
# ----------------------------------------------------------------------
# CMake (Standalone, VS Code, Qt Creator, VS 2026)
# ----------------------------------------------------------------------
CMakeCache.txt
CMakeFiles/
CMakeScripts/
cmake_install.cmake
CTestTestfile.cmake
CPackConfig.cmake
CPackSourceConfig.cmake
install_manifest.txt
compile_commands.json
# Ninja build files (often used with CMake)
.ninja_deps
.ninja_log
build.ninja
# CMake User presets (keep CMakePresets.json, ignore user-specific overrides)
CMakeUserPresets.json
# ----------------------------------------------------------------------
# Visual Studio 2026 (Native Solutions & CMake)
# ----------------------------------------------------------------------
# The .vs folder contains user-specific config and Intellisense databases
.vs/
# User-specific project settings
*.user
*.userosscache
*.sln.docstates
# Suo files (Solution User Options)
*.suo
# Visual Studio cache/temp files
*.aps
*.ncb
*.opensdf
*.sdf
*.cachefile
*.in
*.tlog
# ----------------------------------------------------------------------
# VS Code (C++ & CMake Tools)
# ----------------------------------------------------------------------
# Ignore the entire .vscode directory if you do not want to share settings.
# If you want to share tasks/launch config, comment out `.vscode/` 
# and uncomment the specific lines below.
.vscode/
# -- Specific VS Code ignores (if you un-ignore .vscode/ above) --
# .vscode/settings.json
# .vscode/tasks.json
# .vscode/launch.json
# .vscode/extensions.json
# *.code-workspace
# .history/
# .ionide/
# Microsoft C++ Extension cache
.cm/
# ----------------------------------------------------------------------
# Qt Creator (QMake & CMake)
# ----------------------------------------------------------------------
# QMake specific
*.qmake.stash
Makefile*
# Qt Generated files (Meta-Object Compiler, User Interface Compiler)
# Note: Only ignore these if compiling in-source. Out-of-source builds 
# (handled by build/ ignore above) are preferred.
moc_*.cpp
qrc_*.cpp
ui_*.h
*.moc
# Qt Creator user settings
*.pro.user
*.pro.user.*
CMakeLists.txt.user*
# ----------------------------------------------------------------------
# Autotools (configure, automake)
# ----------------------------------------------------------------------
# Generated configuration files
config.h
config.log
config.status
config.cache
config.guess
config.sub
# Generated Makefiles (keep Makefile.am and Makefile.in if not generated)
# Note: 'Makefile' is already ignored in the Qt section, which covers this.
.deps/
.libs/
autom4te.cache/
aclocal.m4
compile
depcomp
install-sh
missing
stamp-h1
libtool
ltmain.sh
configure
# ----------------------------------------------------------------------
# Vim & Editor Temporary Files
# ----------------------------------------------------------------------
# Swap files
*.swp
*.swo
*~
# Session files
Session.vim
.netrwhist
# ----------------------------------------------------------------------
# OS Generated Files
# ----------------------------------------------------------------------
# Windows
Thumbs.db
ehthumbs.db
Desktop.ini
# Linux / Mac
.DS_Store
.DS_Store?
._*
.directory

# Grok ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Consolidated .gitignore for C++ Projects
# Covers: VS Code (CMake), Visual Studio (native/CMake), Qt Creator (qmake/CMake), CMake standalone, Vim, Make standalone, Autotools
# Platforms: Linux, Windows
# Merge of standard GitHub patterns; duplicates removed
# Global/Prerequisites
*.d
*.dwo
*.tmp
*.log
*.bak
*.swp
*~
*.cache
.cache/
tags
.netrwhist
# OS-specific
.DS_Store
Thumbs.db
ehthumbs.db
Desktop.ini
core
*.core
# C++ Compiled files
*.slo
*.lo
*.o
*.obj
*.gch
*.pch
*.ilk
*.pdb
*.so
*.dylib
*.dll
*.so.*
*.mod
*.smod
*.lai
*.la
*.a
*.lib
*.exe
*.out
*.app
# Build directories (general)
build/
Build/
bld/
[Oo]bj/
[Bb]in/
[Ll]og/
[Ll]ogs/
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]*.s[a-v][a-z]
[._]*.un~
!*.svg
# CMake
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
install_manifest.txt
compile_commands.json
CMakeLists.txt.user*
CMakeScripts
Testing/
CTestTestfile.cmake
_deps/
CMakeUserPresets.json
build-*/
cmake-build-*/
vcpkg_installed/
# Visual Studio (native solutions/projects)
# User-specific
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates
*.env
*.userprefs
mono_crash.*
# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
[Dd]ebug/x64/
[Dd]ebugPublic/x64/
[Rr]elease/x64/
[Rr]eleases/x64/
bin/x64/
obj/x64/
[Dd]ebug/x86/
[Dd]ebugPublic/x86/
[Rr]elease/x86/
[Rr]eleases/x86/
bin/x86/
obj/x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
[Aa][Rr][Mm]64[Ee][Cc]/
[Oo]ut/
Generated\ Files/
# VS cache/options
.vs/
ipch/
*.aps
*.ncb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.VC.db
*.VC.VC.opendb
# Other VS files
*.pdb
*.idb
*.iobj
*.pgc
*.pgd
*.rsp
!Directory.Build.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp_proj
*_wpftmp.csproj
*.tlog
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc
*_i.c
*_p.c
*_h.h
*.meta
*.pgc
*.pgd
# MSTest/NUnit/etc.
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*
*.trx
*.VisualState.xml
TestResult.xml
nunit-*.xml
*.received.*
BenchmarkDotNet.Artifacts/
artifacts/
StyleCopReport.xml
# Packages/NuGet
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nupkg
*.snupkg
project.lock.json
project.fragment.lock.json
*.nuget.props
*.nuget.targets
# Publish
publish/
*.[Pp]ublish.xml
*.azurePubxml
*.pubxml
*.publishproj
PublishScripts/
# Other VS
ClientBin/
~$*
*.dbmdl
*.dbproj.schemaview
*.jfm
*.pfx
*.publishsettings
orleans.codegen.cs
Generated_Code/
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm
ServiceFabricBackup/
*.rptproj.bak
*.mdf
*.ldf
*.ndf
*.rdl.data
*.bim.layout
*.bim_*.settings
*.rptproj.rsuser
*- [Bb]ackup.rdl
*- [Bb]ackup ([0-9]).rdl
*- [Bb]ackup ([0-9][0-9]).rdl
FakesAssemblies/
*.GhostDoc.xml
.ntvs_analysis.dat
node_modules/
*.plg
*.opt
*.vbw
*.dsw
*.dsp
**/*.HTMLClient/GeneratedArtifacts
**/*.DesktopClient/GeneratedArtifacts
**/*.DesktopClient/ModelManifest.xml
**/*.Server/GeneratedArtifacts
**/*.Server/ModelManifest.xml
_Pvt_Extensions
**/.paket/paket.exe
paket-files/
**/.fake/
**/.cr/personal
**/__pycache__/
*.pyc
#tools/**
#!tools/packages.config
*.tss
*.jmconfig
*.btp.cs
*.btm.cs
*.odx.cs
*.xsd.cs
OpenCover/
ASALocalRun/
*.binlog
MSBuild_Logs/
.aws-sam
*.nvuser
**/.mfractor/
**/.localhistory/
.vshistory/
healthchecksdb
MigrationBackup/
**/.ionide/
FodyWeavers.xsd
*.vsix
*.cab
*.msi
*.msix
*.msm
*.msp
*.[Cc]ache
!?*.[Cc]ache/
.bower_components/
*.snk
*.btp.cs
*.btm.cs
*.odx.cs
*.xsd.cs
# Qt Creator (qmake/CMake)
# Objects/libs (already in C++)
/.qmake.cache
/.qmake.stash
*.pro.user
*.pro.user.*
*.qbs.user
*.qbs.user.*
*.moc
moc_*.cpp
moc_*.h
qrc_*.cpp
ui_*.h
*.qmlc
*.jsc
Makefile*
*build-*
*.qm
*.prl
target_wrapper.*
*.autosave
*.qmlproject.user
*.qmlproject.user.*
*creator.user*
*_qmlcache.qrc
object_script.*.Release
object_script.*.Debug
*_plugin_import.cpp
# Autotools/Make standalone
Makefile.in
/ar-lib
/mdate-sh
/py-compile
/test-driver
/ylwrap
.deps/
.dirstamp
autom4te.cache
/autoscan.log
/autoscan-*.log
/aclocal.m4
/compile
/config.cache
/config.guess
/config.h.in
/config.log
/config.status
/config.sub
/configure
/configure.scan
/depcomp
/install-sh
/missing
/stamp-h1
libtool
/ltmain.sh
.libs/
/texinfo.tex
m4/libtool.m4
m4/ltoptions.m4
m4/ltsugar.m4
m4/ltversion.m4
m4/lt~obsolete.m4
# Makefile  # Generated; comment if source-controlled grostig
# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
.history/
# Vim
Session.vim
Sessionx.vim
[._]*.un~
# Session (Vim)
Session.vim
Sessionx.vim
