# ChatGPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
###############################################################################
# Core C/C++ Build Artifacts (Cross-Platform)
###############################################################################

# Object files
*.o
*.obj
*.lo
*.la
*.al
*.pch
*.gch

# Libraries
*.a
*.lib
*.so
*.so.*
*.dylib
*.dll

# Executables
*.exe
*.out
*.app

# Debug / symbol files
*.pdb
*.idb
*.ilk
*.dSYM/
*.su

# Coverage / profiling
*.gcno
*.gcda
*.gcov
*.prof
*.profraw
*.profdata

# Temporary
*.tmp
*.temp
*.log
*.cache
*.bak
*.swp
*.swo
*~

###############################################################################
# CMake (all generators, standalone or IDE driven)
###############################################################################

# Build directories (recommended out-of-source builds)
build/
build-*/
cmake-build-*/
out/
bin/
lib/

# CMake generated files
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake
Testing/
Makefile
CMakeScripts/
_deps/

###############################################################################
# Visual Studio (native projects + CMake integration)
###############################################################################

# VS user files
.vs/
*.VC.db
*.VC.opendb
*.VC.VC.opendb
*.suo
*.user
*.userosscache
*.sln.docstates

# MSBuild
*.tlog
*.lastbuildstate
ipch/

# Visual Studio CMake
CMakeSettings.json
CMakeUserPresets.json

###############################################################################
# VS Code
###############################################################################

.vscode/
*.code-workspace

###############################################################################
# Qt Creator (qmake + CMake)
###############################################################################

# Qt Creator project user files
*.pro.user
*.pro.user.*
*.pri.user
*.creator
*.creator.user
*.creator.user.*

# qmake
Makefile*
*.moc
moc_*.cpp
qrc_*.cpp
ui_*.h

###############################################################################
# GNU Make / Generic Make
###############################################################################

# Dependency files
*.d

###############################################################################
# Autotools
###############################################################################

# Generated by autotools
aclocal.m4
autom4te.cache/
configure
config.log
config.status
config.guess
config.sub
libtool
ltmain.sh
missing
m4/
Makefile.in
depcomp
compile
install-sh

###############################################################################
# Vim
###############################################################################

.*.swp
.*.swo
Session.vim

###############################################################################
# Platform Specific
###############################################################################

# Windows
Thumbs.db
Desktop.ini

# Linux
*.stackdump

###############################################################################
# Archives / Packages
###############################################################################

*.zip
*.tar
*.tar.gz
*.tgz
*.7z

###############################################################################
# Clang / GCC tooling
###############################################################################

.clangd/
.clang-tidy
.clang-format.cache

###############################################################################
# Python (sometimes used for build tooling)
###############################################################################

__pycache__/
*.pyc
